// <auto-generated />
namespace NasleGhalam.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class axillaryBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(axillaryBook));
        
        string IMigrationMetadata.Id
        {
            get { return "201809050540491_axillaryBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
